-- MySQL Script generated by MySQL Workbench
-- 08/09/16 11:31:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EmailForensics
-- -----------------------------------------------------
-- first draft

-- -----------------------------------------------------
-- Table `Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Document` ;

CREATE TABLE IF NOT EXISTS `Document` (
  `Id` VARCHAR(45) NOT NULL,
  `Path` VARCHAR(100) NOT NULL,
  `Content` TEXT(50000) NULL,
  `Timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Entity` ;

CREATE TABLE IF NOT EXISTS `Entity` (
  `Title` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Title`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Snippet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Snippet` ;

CREATE TABLE IF NOT EXISTS `Snippet` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Content` TEXT(50000) NULL,
  `DocumentId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`, `DocumentId`),
  INDEX `fk_Sentence_Email1_idx` (`DocumentId` ASC),
  CONSTRAINT `fk_Sentence_Email1`
    FOREIGN KEY (`DocumentId`)
    REFERENCES `Document` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tag` ;

CREATE TABLE IF NOT EXISTS `Tag` (
  `Spot` VARCHAR(1000) NOT NULL,
  `Rho` DOUBLE NULL,
  `Id` INT NOT NULL AUTO_INCREMENT,
  `EntityTitle` VARCHAR(200) NOT NULL,
  `SnippetId` INT NOT NULL,
  PRIMARY KEY (`Id`, `EntityTitle`, `SnippetId`),
  INDEX `fk_Tag_Entity1_idx` (`EntityTitle` ASC),
  INDEX `fk_Tag_Sentence1_idx` (`SnippetId` ASC),
  CONSTRAINT `fk_Tag_Entity1`
    FOREIGN KEY (`EntityTitle`)
    REFERENCES `Entity` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_Sentence1`
    FOREIGN KEY (`SnippetId`)
    REFERENCES `Snippet` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DocumentTopicDistribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DocumentTopicDistribution` ;

CREATE TABLE IF NOT EXISTS `DocumentTopicDistribution` (
  `DocumentId` VARCHAR(45) NOT NULL,
  `Fraction` DOUBLE NULL,
  `EntityTitle` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`DocumentId`, `EntityTitle`),
  INDEX `fk_TopicDistribution_Email1_idx` (`DocumentId` ASC),
  INDEX `fk_Distribution_Entity1_idx` (`EntityTitle` ASC),
  CONSTRAINT `fk_TopicDistribution_Email1`
    FOREIGN KEY (`DocumentId`)
    REFERENCES `Document` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Distribution_Entity1`
    FOREIGN KEY (`EntityTitle`)
    REFERENCES `Entity` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `Username` VARCHAR(127) NOT NULL,
  `PwdHash` VARCHAR(256) NOT NULL,
  `PwdSalt` VARCHAR(64) NOT NULL,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EntitySelectionAnnotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EntitySelectionAnnotation` ;

CREATE TABLE IF NOT EXISTS `EntitySelectionAnnotation` (
  `DocumentId` VARCHAR(45) NOT NULL,
  `EntityTitle` VARCHAR(200) NOT NULL,
  `Rank` VARCHAR(45) NULL,
  `UserUsername` VARCHAR(127) NOT NULL,
  `Timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`DocumentId`, `EntityTitle`, `UserUsername`, `Timestamp`),
  INDEX `fk_Annotation_Entity1_idx` (`EntityTitle` ASC),
  INDEX `fk_Annotation_User1_idx` (`UserUsername` ASC),
  CONSTRAINT `fk_Annotation_Email1`
    FOREIGN KEY (`DocumentId`)
    REFERENCES `Document` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annotation_Entity1`
    FOREIGN KEY (`EntityTitle`)
    REFERENCES `Entity` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annotation_User1`
    FOREIGN KEY (`UserUsername`)
    REFERENCES `User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Topic` ;

CREATE TABLE IF NOT EXISTS `Topic` (
  `EntityTitle` VARCHAR(200) NOT NULL,
  `Term` VARCHAR(200) NOT NULL,
  `EntityWeight` DOUBLE NULL,
  `TermWeight` DOUBLE NULL,
  PRIMARY KEY (`EntityTitle`, `Term`),
  CONSTRAINT `fk_Topic_Entity1`
    FOREIGN KEY (`EntityTitle`)
    REFERENCES `Entity` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TopicLabelAnnotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TopicLabelAnnotation` ;

CREATE TABLE IF NOT EXISTS `TopicLabelAnnotation` (
  `UserUsername` VARCHAR(127) NOT NULL,
  `EntityTitle` VARCHAR(200) NOT NULL,
  `Timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IsOriginal` TINYINT(1) NULL,
  `IsSelected` TINYINT(1) NULL,
  `DocumentId` VARCHAR(45) NOT NULL,
  `Mode` VARCHAR(45) NULL,
  PRIMARY KEY (`UserUsername`, `EntityTitle`, `Timestamp`, `DocumentId`),
  INDEX `fk_TopiLabelAnnotation_Entity1_idx` (`EntityTitle` ASC),
  INDEX `fk_TopiLabelAnnotation_Email1_idx` (`DocumentId` ASC),
  CONSTRAINT `fk_TopiLabelAnnotation_User1`
    FOREIGN KEY (`UserUsername`)
    REFERENCES `User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TopiLabelAnnotation_Entity1`
    FOREIGN KEY (`EntityTitle`)
    REFERENCES `Entity` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TopiLabelAnnotation_Email1`
    FOREIGN KEY (`DocumentId`)
    REFERENCES `Document` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
